RegistroHoras.WEB/Areas/Admin/Controllers/DiaNaoUtilController.cs
using RegistroHoras.DATA.classes;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Areas.Admin.Controllers
{
    [Authorize]
    public class DiaNaoUtilController : Controller
    {

        private DiaNaoUtilBO DAO = new DiaNaoUtilBO();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CadastroDiaNaoUtil()
        {
            return View();
        }
        public ActionResult CadastrarDiaNaoUtil(DiaNaoUtil diaNaoUtil)
        {
            if (!ModelState.IsValid) return View("CadastroDiaNaoUtil", diaNaoUtil);

            try
            {
                DAO.Salvar(diaNaoUtil);
                return View("Index").ComMensagem("Novo registro adicionado", "alert-success");
            }
            catch(Exception ex)
            {
                return View("CadastroDiaNaoUtil", diaNaoUtil).ComMensagem(ex.Message, "alert-error");
            }
        }
        public ActionResult Excluir(int registro)
        {
            try
            {
                DAO.Excluir(DAO.Get(registro));
                return View("Index").ComMensagem("Registro excluído com sucesso","alert-success");
            }
            catch (Exception ex)
            {
                ViewBag.Mensagem = ex.Message;
                return View("Index");
            }
        }

    }
}

RegistroHoras.WEB/Areas/Admin/Controllers/UsuarioController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles="Administradores")]
    public class UsuarioController : Controller
    {
        // GET: Usuario

        UsuarioBO DAO = new UsuarioBO();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CadastrarUsuario()
        {
            return View();
        }

        public ActionResult SalvarUsuario(Usuario usuario)
        {
            if (!ModelState.IsValid) return View("CadastrarUsuario", usuario);
            try
            {
                DAO.SalvarUsuario(usuario);
                return View("Index");
            }catch(Exception ex)
            {
                return View("CadastrarUsuario", usuario);
            }
        }

        public ActionResult ExcluirUsuario(int colaborador)
        {
            try
            {
                DAO.ExcluirUsuario(DAO.Get(colaborador));
                return View("Index");
            }
            catch(Exception ex) 
            {

                return View("Index");
            }
        }

        public ActionResult ConfigurarUsuario(int colaborador)
        {
            return View(DAO.Get(colaborador));
        }

        public ActionResult AlterarSenha(int colaborador, string Senha)
        {
            try
            {
                DAO.AlterarSenha(colaborador, Senha);
                return View("ConfigurarUsuario", DAO.Get(colaborador)).ComMensagem("Senha alterada com sucesso","alert-success");
            }
            catch (Exception ex)
            {
                return View("ConfigurarUsuario", DAO.Get(colaborador)).ComMensagem(ex.Message,"alert-danger");
            }
            
        }

        public ActionResult AdicionarGrupoAoUsuario(int registroGrupo, int colaborador)
        {
            try
            {
                new GrupoBO().AddUsuarioAoGrupo(colaborador, registroGrupo);
                return View("ConfigurarUsuario", DAO.Get(colaborador));
            }catch(Exception ex)
            {
                return View("ConfigurarUsuario", DAO.Get(colaborador)).ComMensagem("Erro ao adicionar usuário ao grupo." + ex.Message, "alert-danger");
            }
        }

        public ActionResult RemoverGrupoDoUsuario(int registroGrupo, int colaborador)
        {
            try
            {
                new GrupoBO().RemoverUsuarioDoGrupo(colaborador, registroGrupo);
                return View("ConfigurarUsuario", DAO.Get(colaborador));
            }
            catch (Exception ex)
            {
                return View("ConfigurarUsuario", DAO.Get(colaborador)).ComMensagem("Erro ao adicionar usuário ao grupo." + ex.Message, "alert-danger");
            }
        }


    }
}

RegistroHoras.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controle Horas - Administração</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.9.0.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Área Administrativa</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
                    <li>@Html.ActionLink("Colaborador", "Index", "Colaborador")</li>
                    <li>@Html.ActionLink("Feriados", "Index", "DiaNaoUtil")</li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="../navbar/">Default</a></li>
                        <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>*@
                    @if (User.Identity != null)
                    {
                        <li> @Html.ActionLink("Voltar", "Index", "Home", new {area="" }, new { @onclick = "return Confirm('Clique em OK para sair da aplicação.')" })</li>

                    }



                </ul>

            </div>

        </div>

    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year .Net Team JP</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>