RegistroHoras.WEB/Areas/Admin/Controllers/ColaboradorController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Areas.Admin.Controllers
{
    [Authorize]
    public class ColaboradorController : Controller
    {
        ColaboradorBO DAO = new ColaboradorBO();

        // GET: Colaborador
        public ActionResult Index()
        {
            return View(DAO.TodosColaboradores());
        }

        public ActionResult Cadastro()
        {
            return View();
        }


        [Authorize(Roles="Administradores")]
        public ActionResult Editar(int registro)
        {
            return View("Cadastro", DAO.GetColaborador(registro));
        }

        public ActionResult CadastrarColaborador(Colaborador colaborador)
        {
            if (!ModelState.IsValid) return View("Cadastro", colaborador);

            try
            {
                DAO.SalvarColaborador(colaborador);
                return View("Index").ComMensagem("Cadastro efetuado com sucesso","alert-success");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Cadastro");
            }
        }


        public ActionResult Excluir(int registro)
        {
           

            try
            {
                DAO.Excluir(DAO.GetColaborador(registro));
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Cadastro");
            }
        }
    }
}

RegistroHoras.WEB/Controllers/ColaboradorController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Controllers
{
    [Authorize]
    public class ColaboradorController : Controller
    {
        ColaboradorBO DAO = new ColaboradorBO();

        // GET: Colaborador
        public ActionResult Index()
        {
            return View(DAO.TodosColaboradores());
        }

        public ActionResult Cadastro()
        {
            return View();
        }


        [Authorize(Roles="Administradores")]
        public ActionResult Editar(int registro)
        {
            return View("Cadastro", DAO.GetColaborador(registro));
        }

        public ActionResult CadastrarColaborador(Colaborador colaborador)
        {
            if (!ModelState.IsValid) return View("Cadastro", colaborador);

            try
            {
                DAO.SalvarColaborador(colaborador);
                return View("Index").ComMensagem("Cadastro efetuado com sucesso","alert-success");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Cadastro");
            }
        }


        public ActionResult Excluir(int registro)
        {
           

            try
            {
                DAO.Excluir(DAO.GetColaborador(registro));
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Cadastro");
            }
        }
    }
}

RegistroHoras.WEB/Controllers/JornadaColaboradorController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Controllers

{
    [Authorize]
    public class JornadaColaboradorController : Controller
    {
        JornadaColaboradorBO DAO = new JornadaColaboradorBO();
        // GET: JornadaColaborador
        public ActionResult CadastroJornada(int? registroColaborador)
        {
           if(!registroColaborador.HasValue)
               return View(new JornadaColaborador(0));
            return View(new JornadaColaborador(registroColaborador.Value));
        }

  

        public ActionResult SalvarJornada(JornadaColaborador jornada)
        {
            if (!ModelState.IsValid) return View("CadastroJornada", jornada);
            try
            {
                DAO.SalvarJornada(jornada);
                return View("CadastroJornada", new JornadaColaborador(jornada.colaborador));
            }
            catch (Exception)
            {
                return View("CadastroJornada", jornada);
            }
        }

        public ActionResult RemoverJornada(int registro)
        {
            JornadaColaborador jornada = DAO.GetJornadaColaborador(registro);
            try
            {
               
                DAO.ExcluirJornada(jornada);

                return View("CadastroJornada", new JornadaColaborador(jornada.colaborador));
            }
            catch (Exception)
            {
                return View("CadastroJornada");
            }
        }
    }
}

RegistroHoras.WEB/Controllers/RegistroHorasController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Controllers
{
    [Authorize]
    public class RegistroHorasController : Controller
    {
        // GET: RegistroHoras
        private RegistroHorasBO DAO = new RegistroHorasBO();

        public ActionResult Index()
        {
            return View("RegistrarHoraColaborador");
        }


        public ActionResult MesAtual(int registroColaborador)
        {
       
            return View(DAO.RegistroHorasColaboradorMes(registroColaborador, DateTime.Now.Month,DateTime.Now.Year));
        }

        public ActionResult PegarJornadasColaborador(int registroColaborador)
        {
            List<JornadaColaborador> jornadas = new JornadaColaboradorBO().JornadasDoColaborador(registroColaborador);

            return Json(new SelectList(jornadas,"registro","FK_Turno.descricao"));
        }

        public ActionResult SalvarRegistroHora(int jornada, DateTime data, string hora, string Observacao)
        {
            try
            {
                
                string[] strHora = hora.Split(':');
                data = data.AddHours(double.Parse(strHora[0]));
                data = data.AddMinutes(double.Parse(strHora[1]));


                RegistroHoras.DATA.RegistroHoras regHora; 

                //verifica se existe registro para jornada no dia, se existir registra como saída
                regHora = DAO.RegistroJornadaData(jornada, data);
                if (regHora != null)
                {
                    regHora.saida = data;
                    if (Observacao != "" && Observacao != null)
                        regHora.Observacao += Observacao;
                }
                  
                    
            
                else
                    regHora = new DATA.RegistroHoras(jornada, data, Observacao);
             

                DAO.SalvarRegistroHoras(regHora);
                return RedirectToAction("Index", "Home").ComMensagem("Registro realizado com sucesso!", "alert-success") ;

            }
            catch(Exception ex) 
            {
                return View("RegistrarHoraColaborador").ComMensagem(ex.Message, "alert-erro");
            }
           
            
        }

   
        public ActionResult ExcluirRegistroHora(int registroHora, string returnView)
        {
            
            RegistroHoras.DATA.RegistroHoras regHora = DAO.GetRegistroHora(registroHora);
            int colaborador = regHora.FK_JornadaColaborador.colaborador;
            int mes = regHora.entrada.Month;
            int ano = regHora.entrada.Year;
            
            
            try
            {
                DAO.ExcluirRegistroHoras(DAO.GetRegistroHora(registroHora));

                return RedirectToAction(returnView, new { registroColaborador = colaborador });
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                return RedirectToAction(returnView, new { registroColaborador = colaborador });
            }
        }

        public ActionResult MesAtualDetalhes(int registroColaborador)
        {

            return View(DAO.RegistroHorasColaboradorMes(registroColaborador, DateTime.Now.Month, DateTime.Now.Year));
        }


        public PartialViewResult ConsultarRegistroHorasMes(int registroColaborador,int Mes, int Ano)
        {

            return PartialView("PartialRegistroHorasMes", DAO.RegistroHorasColaboradorMes(registroColaborador, Mes, Ano));
        }

        public PartialViewResult ConsutaBancoHorasAno(int colaborador, int ano)
        {
            return PartialView("PartialBancoHoras", DAO.RegistroHorasColaborador(colaborador).Where(r=>r.entrada.Year == ano).ToList());
        }
   

        public ActionResult ListarHorasRegistradasColaborador(int registroColaborador)
        {
            return View(new ColaboradorBO().GetColaborador(registroColaborador));
        }

        public ActionResult ConsultarBancoHoras(int registroColaborador)
        {
            return View(registroColaborador);
        }
    }
}

RegistroHoras.WEB/Areas/Admin/Views/Colaborador/Cadastro.cshtml
@model RegistroHoras.DATA.Colaborador

<h2>Cadastro de Colaborador</h2>

@using (Html.BeginForm("CadastrarColaborador", "Colaborador"))
{
    <div class="row">
        <fieldset>
            <div class="form-group">
                @Html.Label("Nome")
                @Html.TextBoxFor(c => c.nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(c=>c.nome)
            </div>
            <div class="form-group">
                @Html.Label("CPF")
                @Html.TextBoxFor(c => c.cpf, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.cpf)
            </div>
            <div class="form-group">
                @Html.LabelFor(c=>c.regimeDiario)
                @Html.TextBoxFor(c => c.regimeDiario, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.cpf)
            </div>

            @if (Model != null)
            {
                @Html.HiddenFor(c => c.registro)
            }



            <input type="submit" value="Concluir" class="btn btn-primary" />
        </fieldset>

    </div>
    
    
   
}


RegistroHoras.WEB/Areas/Admin/Views/Colaborador/Index.cshtml
@using GridMvc.Html




@{
    ViewBag.Title = "Colaboradores";
}

<h2>Colaboradores</h2>

@Html.ActionLink("Cadastrar", "Cadastro", "", new {@class="btn btn-primary" })

@Html.Grid(new RegistroHoras.DATA.classes.business.ColaboradorBO().TodosColaboradores()).Columns(c =>
{
    c.Add(co => co.nome).Titled("Nome");
    c.Add(co => co.cpf).Titled("CPF");
    c.Add(co => co.regimeDiario).Titled("Horas mensais");
    c.Add().Encoded(false).Sanitized(false).RenderValueAs(d => @Html.ActionLink("jornada", "CadastroJornada", "JornadaColaborador", new { registroColaborador = d.registro }, ""));
    c.Add().Encoded(false).Sanitized(false).RenderValueAs(d => @Html.ActionLink("horas", "ListarHorasRegistradasColaborador", "RegistroHoras", new { registroColaborador = d.registro, area = "" }, ""));
    c.Add().Encoded(false).Sanitized(false).RenderValueAs(d => @Html.ActionLink("editar", "Editar", new { registro = d.registro }));
    c.Add().Encoded(false).Sanitized(false).RenderValueAs(d => @Html.ActionLink("excluir", "Excluir", new { registro = d.registro }, new {@onclick  = "return Confirm('Deseja realmente excluir este colaborador?')"}));
})
