RegistroHoras.WEB/Controllers/LoginController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RegistroHoras.WEB.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login_()
        {
            return View("");
        }

        public ActionResult Signin(string login, string senha)
        {
            try
            {
                Usuario usr = VerificarLogin(login,senha);
                if (usr != null)
                {
                    FormsAuthentication.SetAuthCookie(usr.COLABORADOR.ToString(), false);
                    return RedirectToAction("Index", "Home", new {area="" });

                }

            }
            catch (Exception ex)
            {
                ViewBag.LoginErr = ex.Message;
                
            }

            return View("Login_");
        }

        public Usuario VerificarLogin(string login, string senha)
        {
            Usuario usr = new UsuarioBO().GetUsuario(login, senha);

            if (usr != null)
            {
                if (usr.Ativo)
                {
                    return usr;
                }
                else
                    throw new Exception("Usuário inativo");
            }else
                throw new Exception("Usuário inválido.");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return View("Login_");

        }
    }
}

RegistroHoras.WEB/Controllers/RegistroHorasController.cs
using RegistroHoras.DATA;
using RegistroHoras.DATA.classes.business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistroHoras.WEB.Controllers
{
    [Authorize]
    public class RegistroHorasController : Controller
    {
        // GET: RegistroHoras
        private RegistroHorasBO DAO = new RegistroHorasBO();

        public ActionResult Index()
        {
            return View("RegistrarHoraColaborador");
        }


        public ActionResult MesAtual(int registroColaborador)
        {
       
            return View(DAO.RegistroHorasColaboradorMes(registroColaborador, DateTime.Now.Month,DateTime.Now.Year));
        }

        public ActionResult PegarJornadasColaborador(int registroColaborador)
        {
            List<JornadaColaborador> jornadas = new JornadaColaboradorBO().JornadasDoColaborador(registroColaborador);

            return Json(new SelectList(jornadas,"registro","FK_Turno.descricao"));
        }

        public ActionResult SalvarRegistroHora(int jornada, DateTime data, string hora, string Observacao)
        {
            try
            {
                
                string[] strHora = hora.Split(':');
                data = data.AddHours(double.Parse(strHora[0]));
                data = data.AddMinutes(double.Parse(strHora[1]));


                RegistroHoras.DATA.RegistroHoras regHora; 

                //verifica se existe registro para jornada no dia, se existir registra como saída
                regHora = DAO.RegistroJornadaData(jornada, data);
                if (regHora != null)
                {
                    regHora.saida = data;
                    if (Observacao != "" && Observacao != null)
                        regHora.Observacao += Observacao;
                }
                  
                    
            
                else
                    regHora = new DATA.RegistroHoras(jornada, data, Observacao);
             

                DAO.SalvarRegistroHoras(regHora);
                return RedirectToAction("Index", "Home").ComMensagem("Registro realizado com sucesso!", "alert-success") ;

            }
            catch(Exception ex) 
            {
                return View("RegistrarHoraColaborador").ComMensagem(ex.Message, "alert-erro");
            }
           
            
        }

   
        public ActionResult ExcluirRegistroHora(int registroHora, string returnView)
        {
            
            RegistroHoras.DATA.RegistroHoras regHora = DAO.GetRegistroHora(registroHora);
            int colaborador = regHora.FK_JornadaColaborador.colaborador;
            int mes = regHora.entrada.Month;
            int ano = regHora.entrada.Year;
            
            
            try
            {
                DAO.ExcluirRegistroHoras(DAO.GetRegistroHora(registroHora));

                return RedirectToAction(returnView, new { registroColaborador = colaborador });
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                return RedirectToAction(returnView, new { registroColaborador = colaborador });
            }
        }

        public ActionResult MesAtualDetalhes(int registroColaborador)
        {

            return View(DAO.RegistroHorasColaboradorMes(registroColaborador, DateTime.Now.Month, DateTime.Now.Year));
        }


        public PartialViewResult ConsultarRegistroHorasMes(int registroColaborador,int Mes, int Ano)
        {

            return PartialView("PartialRegistroHorasMes", DAO.RegistroHorasColaboradorMes(registroColaborador, Mes, Ano));
        }

        public PartialViewResult ConsutaBancoHorasAno(int colaborador, int ano)
        {
            return PartialView("PartialBancoHoras", DAO.RegistroHorasColaborador(colaborador).Where(r=>r.entrada.Year == ano).ToList());
        }
   

        public ActionResult ListarHorasRegistradasColaborador(int registroColaborador)
        {
            return View(new ColaboradorBO().GetColaborador(registroColaborador));
        }

        public ActionResult ConsultarBancoHoras(int registroColaborador)
        {
            return View(registroColaborador);
        }
    }
}

RegistroHoras.WEB/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

RegistroHoras.WEB/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

RegistroHoras.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Horas</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")"></script>
    <link href="@Url.Content("~/Content/jquery-ui.theme.css")" rel="stylesheet" />

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="@Url.Content("~/Scripts/js.js")"></script>
   
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-1.9.0.min.js"></script>
    <script src="~/Scripts/jquery.mask.js"></script>
    @*<script src="https://raw.githubusercontent.com/igorescobar/jQuery-Mask-Plugin/master/src/jquery.mask.js" type="text/javascript" language="javascript"></script>*@
   
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/images/favicon.ico">
</head>
<body>
 
   
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Controle Horas</a>
            </div>
            @if (User.Identity.IsAuthenticated) { 
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     <li>@Html.ActionLink("Registrar Hora", "Index", "RegistroHoras")</li>
                     
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Relatórios <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Mês Atual", "MesAtual", "RegistroHoras", new { registroColaborador = int.Parse(User.Identity.Name) }, "")</li>
                            <li>@Html.ActionLink("Mês Atual Detalhado", "MesAtualDetalhes", "RegistroHoras", new { registroColaborador = int.Parse(User.Identity.Name) }, "")</li>
                            <li>@Html.ActionLink("Registros por Mês", "ListarHorasRegistradasColaborador", "RegistroHoras", new { registroColaborador = int.Parse(User.Identity.Name) }, "")</li>
                            <li>@Html.ActionLink("Banco de Horas", "ConsultarBancoHoras", "RegistroHoras", new { registroColaborador = int.Parse(User.Identity.Name) }, "")</li>
                            
                                @*<li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li class="divider"></li>
                                <li><a href="#">One more separated link</a></li>*@
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="../navbar/">Default</a></li>
                    <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>*@
                   @if (User.Identity != null)
                   {
                    <li> @Html.ActionLink("Sair", "Logout", "Login", "", new { @onclick = "return Confirm('Clique em OK para sair da aplicação.')" })</li>
                    
                   }
                        
                   
                    
                </ul>

            </div>
            }
        </div>
        
    </div>
    

    @RenderSection("scripts",false)

    <div class="container body-content">
        @{Html.RenderPartial("_Mensagem");}
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;.NET Team JP @DateTime.Now.Year </p>
        </footer>
    </div>


</body>
</html>

RegistroHoras.WEB/Views/Shared/_Mensagem.cshtml
<script src="~/Scripts/bootstrap.min.js"></script>

@if (TempData["Mensagem"] != null)
{
    <div style="padding-top:10px">
        <div class="alert @Html.Raw(TempData["ClasseAlert"].ToString())">
            <b>@TempData["Mensagem"]</b>
            <button type="button" class="close" data-dismiss="alert">×</button>
        </div>
    </div>
}